project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "OLIVE ORBIT"
  author:
    - RIDDHI DINESH OZA (ro2418)
    - RAMON CIUTAD (rc3714)
  repo-url: https://github.com/RIDDHIOZA25/olive-oil-data-viz
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: sketchy
    code-fold: true
